services:
  minioservice:
    image: minio/minio:latest
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address :9001

  global-db:
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: global_db
      MYSQL_ROOT_PASSWORD: Mythi@2024
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

    ports:
      - '3307:3306'

volumes:
  minio-data:
